POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjZhYjE1ZGRlZGE5NTk5MGMyZjkzZWMwZSIsImlhdCI6MTc5MDA4ODQ5Mn0.Wuz4Fh8GV_38HtxZpMJntDvDm4Tg2aIaQi1ld_DK93M

{
    "title": "Ovo mi je prvi blog",
    "author": "Matej Milankov",
    "url": "http://localhost:3003/api/blogs/1",
    "likes": 0,
    "userId": "6ab15ddeda95990c2f93ec0e"
}